package utils;

public enum CluStreamAlgorithmImplementation {
	NO_PARALLEL, 
	JAVA_PARALLEL_SYNTHESES,
	JAVA_PARALLEL_FEATURES,
	JAVA_PARALLEL_BOTH,
	SPARK_PARALLEL_SYNTHESES,
	SPARK_PARALLEL_FEATURES,
	SPARK_PARALLEL_BOTH,
	JAVA_PARALLEL_BUFFER,
	SPARK_PARALLEL_BUFFER
}
